# Generated by Django 2.1.1 on 2018-09-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica',
            name='nombre',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='categoria',
            name='flag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rubrocomercio',
            name='nombre',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tipocodigo',
            name='nombre',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='unidaddemedida',
            name='nombre',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='caracteristicaproducto',
            name='valor',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='codigoproducto',
            name='valor',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='medidaproducto',
            name='valor',
            field=models.FloatField(default=''),
        ),
    ]
