# Generated by Django 2.1.1 on 2018-09-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20180929_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='nombre',
            field=models.TextField(default=''),
        ),
    ]
