# Generated by Django 2.1.1 on 2018-09-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_comercio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='caracteristicas',
            field=models.ManyToManyField(blank=True, through='backend.CaracteristicaProducto', to='backend.Caracteristica'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='backend.Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigos',
            field=models.ManyToManyField(blank=True, through='backend.CodigoProducto', to='backend.TipoCodigo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='comercios',
            field=models.ManyToManyField(blank=True, to='backend.Comercio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='medidas',
            field=models.ManyToManyField(blank=True, through='backend.MedidaProducto', to='backend.UnidadDeMedida'),
        ),
    ]
