<<<<<<< HEAD
# Generated by Django 2.1.1 on 2018-10-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20181004_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
=======
# Generated by Django 2.1.1 on 2018-10-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20181004_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
>>>>>>> d52a33efb512735425f940ba06297e9d2726dffb
