# Generated by Django 2.1.1 on 2018-10-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_categoria_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoproducto',
            name='valor',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigos',
            field=models.ManyToManyField(through='backend.CodigoProducto', to='backend.TipoCodigo'),
        ),
        migrations.AlterField(
            model_name='tipocodigo',
            name='nombre',
            field=models.CharField(max_length=128),
        ),
    ]
