# Generated by Django 2.1.1 on 2018-10-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20181014_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='codigos',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='comercios',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='medidas',
        ),
    ]
