# Generated by Django 2.1.1 on 2018-10-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20181016_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='backend.Categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='comercios',
            field=models.ManyToManyField(blank=True, to='backend.Comercio'),
        ),
    ]
