# Generated by Django 2.1.1 on 2018-10-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_producto_comercios'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='comercios',
            field=models.ManyToManyField(blank=True, to='backend.Comercio'),
        ),
    ]
