# Generated by Django 2.1.1 on 2018-10-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_producto_codigos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigos',
        ),
        migrations.AlterField(
            model_name='codigoproducto',
            name='valor',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tipocodigo',
            name='nombre',
            field=models.TextField(default=''),
        ),
    ]
