# Generated by Django 2.1.1 on 2018-10-17 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20181016_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='medidas',
        ),
    ]
