# Generated by Django 2.1.1 on 2018-10-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_producto_medidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='medidas',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigos',
            field=models.ManyToManyField(blank=True, through='backend.CodigoProducto', to='backend.TipoCodigo'),
        ),
    ]
