# Generated by Django 2.1.1 on 2018-10-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20181016_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='medidas',
            field=models.ManyToManyField(blank=True, through='backend.MedidaProducto', to='backend.UnidadDeMedida'),
        ),
    ]
