# Generated by Django 2.1.2 on 2018-10-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20181019_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigos',
            field=models.ManyToManyField(through='backend.CodigoProducto', to='backend.TipoCodigo'),
        ),
    ]
