# Generated by Django 2.1.2 on 2018-10-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20181019_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigos',
        ),
    ]
