# Generated by Django 2.1.2 on 2018-10-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_producto_codigos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidaproducto',
            name='valor',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tipocodigo',
            name='nombre',
            field=models.TextField(default=''),
        ),
    ]
