# Generated by Django 2.1.2 on 2018-10-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20181019_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='medidas',
            field=models.ManyToManyField(blank=True, through='backend.MedidaProducto', to='backend.UnidadDeMedida'),
        ),
    ]
